version: '3'

services:
  web:
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - student_network

  api:
    image: student
    ports:
      - "5001:5000"
    volumes:
      - ./student_age.json:/data/student_age.json
    networks:
      - student_network

networks:
  student_network:
    drive: bridge  
